#!/usr/bin/env python3
"""Extract Halley's known Rune configuration paths into Nix data."""

import argparse
import json
from pathlib import Path
import re


SCHEMA_SETS = (
    "known_top_sections",
    "ignored_sections",
    "sections",
    "scalars",
)


def array_body(source: str, name: str) -> str:
    declaration = re.search(
        rf"let\s+{re.escape(name)}\s*=\s*HashSet::from\(\[",
        source,
    )
    if declaration is None:
        raise ValueError(f"could not find {name} in validator source")

    body_start = declaration.end()
    depth = 1
    for index in range(body_start, len(source)):
        if source[index] == "[":
            depth += 1
        elif source[index] == "]":
            depth -= 1
            if depth == 0:
                return source[body_start:index]
    raise ValueError(f"unterminated array for {name}")


def extract_paths(source: str, name: str) -> list[str]:
    return sorted(set(re.findall(r'"([^"\\]*(?:\\.[^"\\]*)*)"', array_body(source, name))))


def nix_list(values: list[str], indent: str) -> str:
    return "\n".join(f"{indent}{json.dumps(value)}" for value in values)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("validator", type=Path, help="Path to parse/validate.rs")
    parser.add_argument("output", type=Path, help="Generated .nix output path")
    args = parser.parse_args()

    source = args.validator.read_text()
    schema = {name: extract_paths(source, name) for name in SCHEMA_SETS}
    lines = [
        "# Generated by scripts/extract-halley-schema.py. Do not edit manually.",
        "{",
    ]
    for name in SCHEMA_SETS:
        lines.extend((f"  {name} = [", nix_list(schema[name], "    "), "  ];"))
    lines.append("}")
    args.output.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
